# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\User\PycharmProjects\task-solve\design.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(375, 175)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 371, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 90, 371, 31))
        self.label_2.setObjectName("label_2")
        self.audit_month = QtWidgets.QPushButton(self.centralwidget)
        self.audit_month.setGeometry(QtCore.QRect(50, 50, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.audit_month.setFont(font)
        self.audit_month.setObjectName("audit_month")
        self.audit_week = QtWidgets.QPushButton(self.centralwidget)
        self.audit_week.setGeometry(QtCore.QRect(210, 50, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.audit_week.setFont(font)
        self.audit_week.setObjectName("audit_week")
        self.teach_month = QtWidgets.QPushButton(self.centralwidget)
        self.teach_month.setGeometry(QtCore.QRect(50, 130, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.teach_month.setFont(font)
        self.teach_month.setObjectName("teach_month")
        self.teach_week = QtWidgets.QPushButton(self.centralwidget)
        self.teach_week.setGeometry(QtCore.QRect(210, 130, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.teach_week.setFont(font)
        self.teach_week.setObjectName("teach_week")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Процентные данные загруженности аудиторий:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Среднее количество пар у преподавателя:</span></p></body></html>"))
        self.audit_month.setText(_translate("MainWindow", "по месяцам"))
        self.audit_week.setText(_translate("MainWindow", "по неделям"))
        self.teach_month.setText(_translate("MainWindow", "в месяц"))
        self.teach_week.setText(_translate("MainWindow", "в неделю"))
